apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-auth
  template:
    metadata:
      labels:
        app: account-auth
    spec:
      containers:
        - name: account-auth
          image: 254361319875.dkr.ecr.us-east-1.amazonaws.com/fishing-app:auth
          ports:
            - containerPort: 4001

          envFrom:
            - configMapRef:
                name: db-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: account-auth
spec:
  selector:
    app: account-auth
  ports:
    - port: 4001
      targetPort: 4001
  type: ClusterIP