apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameplay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gameplay
  template:
    metadata:
      labels:
        app: gameplay
    spec:
      containers:
        - name: gameplay
          image: 254361319875.dkr.ecr.us-east-1.amazonaws.com/fishing-app:gameplay
          ports:
            - containerPort: 4002

          env:
            - name: DB_HOST
              value: "RDS Endpoint"

            - name: DB_PORT
              value: "3306"

            - name: DB_USER
              value: "fishadmin"

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password

            - name: DB_NAME
              value: "fishing_game"