apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameplay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gameplay
  template:
    metadata:
      labels:
        app: gameplay
    spec:
      containers:
        - name: gameplay
          image: 254361319875.dkr.ecr.us-east-1.amazonaws.com/fishing-app:gameplay
          ports:
            - containerPort: 4002

          envFrom:
            - configMapRef:
                name: db-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: gameplay
spec:
  selector:
    app: gameplay
  ports:
    - port: 4002
      targetPort: 4002
  type: ClusterIP