apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-profile
  template:
    metadata:
      labels:
        app: player-profile
    spec:
      containers:
        - name: player-profile
          image: 254361319875.dkr.ecr.us-east-1.amazonaws.com/fishing-app:profile-v0.1
          ports:
            - containerPort: 4003

          envFrom:
            - configMapRef:
                name: db-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: player-profile
spec:
  selector:
    app: player-profile
  ports:
    - port: 4003
      targetPort: 4003
  type: ClusterIP